version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CASSANDRA_HOST=cassandra-cluster


networks:
  overlay:
    external: true
    name: story-network